### ISSUE TITLE
[BUG] import_weekly_rosters function thowing ValueError

### ISSUE THREAD

**Issue by nateb7722** [nflverse/nfl_data_py#113] opened 2024-09-18 20:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### If this is a data issue, have you tried clearing your nflverse cache?

I am not using an nflverse R package (nflreadr, nflfastR) to access this data.

### What version of the package do you have?

0.3.2

### Describe the bug

when running this function on a single season there is no error, but when putting multiple years in, it throws an error

### Reprex

```r
roster = nfl_new.import_weekly_rosters([i for i in range(2022,2024)])

error:
Traceback (most recent call last):
  File "...interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-68-4f57e1e7a23a>", line 1, in <module>
    roster = nfl_new.import_weekly_rosters([i for i in range(2022,2024)])
  File "...lib\site-packages\nfl_data_py\__init__.py", line 474, in import_weekly_rosters
    rosters["age"] = ((roster_dates - rosters.birth_date).dt.days / 365.25).round(3)
  File "...\lib\site-packages\pandas\core\frame.py", line 4299, in __setitem__
    self._set_item(key, value)
  File "...\lib\site-packages\pandas\core\frame.py", line 4512, in _set_item
    value, refs = self._sanitize_column(value)
  File "...\lib\site-packages\pandas\core\frame.py", line 5250, in _sanitize_column
    return _reindex_for_setitem(value, self.index)
  File "...\lib\site-packages\pandas\core\frame.py", line 12679, in _reindex_for_setitem
    raise err
  File "...\lib\site-packages\pandas\core\frame.py", line 12674, in _reindex_for_setitem
    reindexed_value = value.reindex(index)._values
  File "...\lib\site-packages\pandas\core\series.py", line 5144, in reindex
    return super().reindex(
  File "...\lib\site-packages\pandas\core\generic.py", line 5607, in reindex
    return self._reindex_axes(
  File "...\lib\site-packages\pandas\core\generic.py", line 5630, in _reindex_axes
    new_index, indexer = ax.reindex(
  File "...\lib\site-packages\pandas\core\indexes\base.py", line 4429, in reindex
    raise ValueError("cannot reindex on an axis with duplicate labels")
ValueError: cannot reindex on an axis with duplicate labels
```

### Expected Behavior

function to return combine df for all years in list

### nflverse_sitrep

```r
NA
```

**Comment by alecglen** [comment] 2024-09-18 20:50
Duplicate of https://github.com/nflverse/nfl_data_py/issues/75, fixed in 0.3.3 dev release.

@nateb7722 run the command below in your environment and that should fix it.
```
pip install --force-reinstall nfl-data-py@git+https://github.com/nflverse/nfl_data_py.git@v0.3.3
```

**Closed by alecglen** 2024-09-18 20:50 UTC
